### ISSUE TITLE
Module quarkus-langchain4j-integration-test-openai in 1.7 fails to compile with Quarkus 3.33.2

### ISSUE THREAD

**Issue by fedinskiy** [quarkiverse/quarkus-langchain4j#2633]
How to reproduce:
1. `git clone -b 1.7 git@github.com:quarkiverse/quarkus-langchain4j.git reproducer && cd reproducer`
2. `./mvnw -B --no-transfer-progress clean install -DskipTests -Dquarkus.version=3.33.2`

The error: 
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.26.3:build (default) on project quarkus-langchain4j-integration-test-openai: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit threw an exception: java.lang.NoSuchMethodError: 'boolean io.quarkus.dev.console.TerminalUtils.hasColorSupport()'
[ERROR] 	at io.quarkus.runtime.logging.LoggingSetupRecorder.isColorEnabled(LoggingSetupRecorder.java:878)
[ERROR] 	at io.quarkus.runtime.logging.LoggingSetupRecorder.configureConsoleHandler(LoggingSetupRecorder.java:608)
[ERROR] 	at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeBuildTimeLogging(LoggingSetupRecorder.java:346)
[ERROR] 	at io.quarkus.deployment.logging.LoggingResourceProcessor.setupLoggingRuntimeInit(LoggingResourceProcessor.java:341)
[ERROR] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:242)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1474)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

```

Given, that langchain4j 1.7 is used by Quarkus platform 3.33 together with Quarkus Core 3.33, they should be binary compatible.

**Comment by fedinskiy** [comment]
My bad, for integration tests there should be `-Dquarkus.platform.version=3.33.2` option as well

**Comment by geoand** [comment]
👍🏽
